apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhooq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jhooq
  template:
    metadata:
      labels:
        app: jhooq
    spec:
      containers:
        - name: springboot
          image: snowpanther37/vooddle
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jhooq