FROM node

WORKDIR /app

RUN npm install -g forever

COPY package.json /app
RUN npm install
RUN mv /app/node_modules /node_modules

COPY . .

ENV PORT 3000
ENV NODE_VERSION=16.13.2

EXPOSE $PORT

CMD [ "forever", "-w", "server.js"]